name: CD ‚ú®

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI ‚ú®"]
    types: [completed]
    branches: [main, prod]

env:
  REGISTRY: ghcr.io
  COMMIT_SHA: ${{ github.sha }}
  IMAGE_NAME_API: ${{ github.repository }}/api
  IMAGE_NAME_WEB_SPA: ${{ github.repository }}/web-spa
  IMAGE_NAME_WEB_SSR: ${{ github.repository }}/web-ssr
  API_URL: ${{ secrets.API_URL }}

jobs:
  setup:
    name: üõ†Ô∏è Setup
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' }}
    outputs:
      node-version: 22.14.0
      pnpm-version: 10.5.2
    steps:
      - name: üì• Checkout repository
        uses: actions/checkout@v4

      - name: üîß Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: 22.14.0
          pnpm-version: 10.5.2

      - name: üìÅ Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: üì¶ Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: üìö Install dependencies
        run: pnpm install

      - name: üíæ Cache workspace
        uses: actions/cache@v3
        with:
          path: .
          key: workspace-${{ github.sha }}

  deploy-api-docker:
    name: üê≥ Deploy API Docker Image
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: üìÇ Restore workspace
        uses: actions/cache@v3
        with:
          path: .
          key: workspace-${{ github.sha }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}
          tags: |
            latest
            type=sha,format=short,prefix=

      - name: Build and push API Docker image
        id: push-api
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}
          subject-digest: ${{ steps.push-api.outputs.digest }}
          push-to-registry: true

  deploy-web-spa-docker:
    name: üê≥ Deploy Web SPA Docker Image
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: üìÇ Restore workspace
        uses: actions/cache@v3
        with:
          path: .
          key: workspace-${{ github.sha }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-spa
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB_SPA }}
          tags: |
            latest
            type=sha,format=short,prefix=

      - name: Build and push Web SPA Docker image
        id: push-spa
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./apps/web-spa/Dockerfile
          push: true
          tags: ${{ steps.meta-spa.outputs.tags }}
          build-args: |
            VITE_API_URL=${{ env.API_URL }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB_SPA }}
          subject-digest: ${{ steps.push-spa.outputs.digest }}
          push-to-registry: true

  deploy-web-ssr-docker:
    name: üê≥ Deploy Web SSR Docker Image
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: üìÇ Restore workspace
        uses: actions/cache@v3
        with:
          path: .
          key: workspace-${{ github.sha }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-ssr
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB_SSR }}
          tags: |
            latest
            type=sha,format=short,prefix=

      - name: Build and push Web SSR Docker image
        id: push-ssr
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./apps/web-ssr/Dockerfile
          push: true
          tags: ${{ steps.meta-ssr.outputs.tags }}
          build-args: |
            VITE_API_URL=${{ env.API_URL }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB_SSR }}
          subject-digest: ${{ steps.push-ssr.outputs.digest }}
          push-to-registry: true
